[workspace]
resolver = "2"
members = [
    "crates/kage-core",
    "crates/kage-cdp",
    "crates/kage-storage",
    "crates/kage-context",
    "crates/kage-plugin",
    "src-tauri",
]

[workspace.package]
version = "0.2.1"
edition = "2021"
authors = ["Hardik Bhaskar <hardik.bhaskar2010@gmail.com>"]
license = "Proprietary"
repository = "https://github.com/HardikBhaskar2010/Kage"
